#!bin/bash
set -e
certbot certonly \
        -n \
        -m email@stephen-cresswell.net \
        --agree-tos \
        --webroot \
        --staging \
        -w /var/www \
        -d stephen-cresswell.net \
        -d www.stephen-cresswell.net \
        -d stage.stephen-cresswell.net


